import type { Metadata } from "next";
import { Handlee } from 'next/font/google';
import "./globals.css";
import ParticlesBackground from './components/ParticlesBackground';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const handlee = Handlee({
  subsets: ['latin'],
  weight: '400',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${handlee.className}`} >
        <ParticlesBackground />
        <div className="h-full w-full" style={{ position: 'relative', zIndex: 1 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
